### ISSUE TITLE
Improve Hnsw cost estimate

### ISSUE THREAD

**Issue by Ngalstyan4** [lanterndata/lanterndb#14]
Properly implement postgres index [cost estimation](https://github.com/lanterndata/lanterndb/blob/65353dc78908f19d63de4e8b050c2b59860d7fca/src/hnsw.c#L44-L126) for postgres query planner

Resources

- Index cost estimation`  https://www.postgresql.org/docs/current/index-cost-estimation.html

**Comment by yoloVoe** [comment]
Will try to get to this by Aug 20.

**Comment by yoloVoe** [comment]
Commits that make progress on this task.

- First commit https://github.com/yoloVoe/lanterndb/commit/bfebc9f513f71304652ae43f4cfdf5d3bd6b1076 essentially just adds some logs to current implementation so we can track of some relevant internal state in existing tests.
  If we don't want this in production, maybe we can add a compiler flag/macro that only enables it during test runs.
  This commit can be submitted as PR already.
- Second commit https://github.com/yoloVoe/lanterndb/commit/0dfc36a6b5a6de3cddf67ead6365a5a5d8a0982f improves the hnsw cost estimate. Some items that need to be done before this can be submitted as PR: 1) Update tests, 2) Sanity-check values around edge-cases (LIMIT > number of vectors in index, etc)


There are further improvements we can do on top of the implementation above, but to gain confidence in improvements, we'd also need to add more test cases. Ideally, we'd be able to unit test the cost estimate function too.
