### ISSUE TITLE
Add a new distance function to LanternDB index

### ISSUE THREAD

**Issue by Ngalstyan4** [lanterndata/lanterndb#34]
Currently we only support l2-squared distance function ([sql](https://github.com/lanterndata/lanterndb/blob/main/sql/lanterndb.sql#L19-L22), [c](https://github.com/lanterndata/lanterndb/blob/db801adced391cbb57ecde5c333635dc12f94e62/src/hnsw.c#L226-L231) refs)through usearch.
We should add other distance functions such as l1, l2, hamming distance, cosine distance, etc

**Comment by yoloVoe** [comment]
Can I claim this Issue till August 20th? will try to work on this meanwhile

**Comment by yoloVoe** [comment]
There is already a PR for this out: https://github.com/lanterndata/lanterndb/pull/42

Doesn't cover hamming distance but the rest is covered it seems.
