### ISSUE TITLE
Update tests to separate `vector` tests and use native arrays by default

### ISSUE THREAD

**Issue by var77** [lanterndata/lanterndb#57]
Currently some of our tests are using `vector` type which is creating a dependency over `pgvector`.

We should convert the tests to use native postgres `real[]` type by default and separate tests using `vector` type in test files named `$testname_vector.sql`.

By doing this we will be able to detect if `pgvector` extension exists in the system and include vector tests in our test schedule as well. This checks can be done in `run_all_tests.sh` file.

**Comment by dqii** [comment]
Working on this one.
