### ISSUE TITLE
Bug: Compilation issue with a defined __AVX512__ without _Float16 support.

### ISSUE THREAD

**Issue by grubdragon** [lanterndata/lanterndb#59]
Currently compilation fails for my machine since it has `__AVX512F__` defined, but environment does not support `_Float16`. See code below:

https://github.com/Ngalstyan4/usearch/blob/d7b1b571d4c2c6b940e7a9ff871e3f5c7b35d3d9/include/usearch/index_punned_helpers.hpp#L23-L35

There is another underlying issue in the else condition of the same code, since the code throws away the environment's choice, even if USEARCH_USE_NATIVE_F16 is pre-defined,

A better choice is to -
- Directly check the thing we require directly i.e. instead of checking if `__AVX512__` is defined, we check if `_Float16` is defined.
-  Handle the user choice in the else condition as well

**Comment by Ngalstyan4** [comment]
Thanks @grubdragon! My understanding was that the original code was fine for the second case as it only threw away user's choice if a better system alternative was detected. But will look into it more once I am in a setting where I can reproduce the issue. 

Merged the PR for now!
