### ISSUE TITLE
Feature: Cache downloaded files while running tests, and check their integrity before using them 

### ISSUE THREAD

**Issue by grubdragon** [lanterndata/lanterndb#63]
For every test being run using `run_all_tests.sh`, data files are being downloaded. This can be sped up by checking if the file is downloaded and checking its' hash, before proceeding with the rest of the code.

This saves a few seconds every run.

**Comment by var77** [comment]
Hi @grubdragon thanks for the issue!

I guess we currently have a check if the temp file directory exists we do not download the files again, you can see it [here](https://github.com/lanterndata/lanterndb/blob/main/scripts/run_all_tests.sh#L19). 
But yes current approach needs some improvements:
- Check each file separately if exists (currently if we add a new file the temp directory needs to be removed manually)
- For updating the existing test files, checking the hashes may still require to get the file from remote each time and compare the hash with local one (at least this is what came in my mind). So we can just add some flag to our test runner like `--reset` or `--no-cache` to download the test files again.

**Comment by Ngalstyan4** [comment]
Another option is to add the downloaded test files to cmake as targets so cmake machinery will re-download them whenever needed.

**Comment by grubdragon** [comment]
As I had digged in to the Cmake, I realized that the tmp dir is being cleared with every WSL (Windows Subsystem for Linux) restart, which makes it download everytime I try test (I have never tried test twice during the same uptime since tests aren't working for me - user issues).

**Comment by Ngalstyan4** [comment]
`tmp` is a standard place for temporary files and our test downloads are temporary files.
If you want tmp files to live longer, you could probably change the cleanup policy for the folder.
At some point we may move the downloaded test files to the cmake build directory. But I think the current approach is fine for now.
